# To use:
# Run "docker-compose build" to rebuild the app container.
# Run "docker-compose run -u $(id -u ${USER}):$(id -g ${USER}) --rm php84 composer install" to install dependencies.
# Run "docker-compose run  -u $(id -u ${USER}):$(id -g ${USER})--rm php84 vendor/bin/pest" to run the test script on 8.4.
# Run "docker-compose down -v" to fully wipe everything and start over.
# Run "docker-compose run -u $(id -u ${USER}):$(id -g ${USER}) --rm php84 bash" to log into the container to run tests selectively.
services:
    php84:
        build: ./docker/php/84
        volumes:
            - ~/.composer:/.composer
            - .:/usr/src/myapp
            - ./docker/php/84/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            XDEBUG_MODE: "develop,debug"
            XDEBUG_CONFIG: "client_host=${HOST_IP:-host.docker.internal} idekey=${IDE_KEY:-PHPSTORM} client_port=${XDEBUG_PORT:-9003} discover_client_host=1 start_with_request=1"
    profile:
        build: ./docker/php/84
        volumes:
            - .:/usr/src/myapp
            - ./docker/php/84/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        environment:
            XDEBUG_MODE: "develop,profile"
            XDEBUG_CONFIG: "client_host=${HOST_IP:-host.docker.internal} idekey=${IDE_KEY:-PHPSTORM} client_port=${XDEBUG_PORT:-9003} discover_client_host=1 start_with_request=1"
