---
name: Quality Assurance
on:
    push:
        branches: ['main']
    pull_request: ~

jobs:
    tests:
        name: Tests on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.4']
                composer-flags: ['']
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  tools: composer:v2
            - run: composer install --no-progress ${{ matrix.composer-flags }}
            - run: vendor/bin/pest --coverage

    php-cs-fixer:
        name: Code Style on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.4']
                composer-flags: ['']
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:v2
            - run: composer install --no-progress ${{ matrix.composer-flags }}
            - run: vendor/bin/php-cs-fixer check --diff
